export const AKKREDITATSIYA_LOAD_DATA = "AKKREDITATSIYA_LOAD_DATA";
export const AKKREDITATSIYA_SET_DATA = "AKKREDITATSIYA_SET_DATA";
export const AKKREDITATSIYA_ACTIVATE_SPINNER = "AKKREDITATSIYA_ACTIVATE_SPINNER";
export const AKKREDITATSIYA_DEACTIVATE_SPINNER = "AKKREDITATSIYA_DEACTIVATE_SPINNER";