// for redux-saga
export const LOAD_GALLERY_DATA = 'LOAD_GALLERY_DATA';

// for redux-reducer
export const SET_GALLERY_DATA = 'SET_GALLERY_DATA';

export const GALLERY_SPINNER_ACTIVATE = 'GALLERY_SPINNER_ACTIVATE';
export const GALLERY_SPINNER_DEACTIVATE = 'GALLERY_SPINNER_DEACTIVATE';

export const CHANGE_ERROR_GALLERY_IMAGE = 'CHANGE_ERROR_GALLERY_IMAGE';
export const CHANGE_GALLERY_FILTER_VALUE = 'CHANGE_FILTER_VALUE';

export const SET_GALLERY_IMAGE_TITLES = 'SET_GALLERY_IMAGE_TITLES';

