// for redux-saga
export const LOAD_GALLERY_DATA = 'LOAD_GALLERY_DATA';

// for redux-reducer
export const SET_GALLERY_DATA = 'SET_GALLERY_DATA';
export const GALLERY_SPINNER_ACTIVATE = 'GALLERY_SPINNER_ACTIVATE';
export const GALLERY_SPINNER_DEACTIVATE = 'GALLERY_SPINNER_DEACTIVATE';

