// for redux-saga
export const LOAD_GLORY_BOARD_DATA = 'LOAD_GLORY_BOARD_DATA';

// for redux-reducer
export const SET_GLORY_BOARD_DATA = 'SET_GLORY_BOARD_DATA';
export const GLORY_BOARD_SPINNER_ACTIVATE = 'GLORY_BOARD_SPINNER_ACTIVATE';
export const GLORY_BOARD_SPINNER_DEACTIVATE = 'GLORY_BOARD_SPINNER_DEACTIVATE';
export const GLORY_BOARD_CURRENT_FILTER_VALUE = 'GLORY_BOARD_CURRENT_FILTER_VALUE';
export const CHANGE_GLORY_BOARD_IMAGE = 'CHANGE_GLORY_BOARD_IMAGE';

