// for redux saga
export const LOAD_HOME_ABOUT_DATA = 'LOAD_HOME_ABOUT_DATA';
export const HOME_CONTENT_SPINNER_ACTIVATE = 'HOME_CONTENT_SPINNER_ACTIVATE';
export const HOME_CONTENT_SPINNER_DEACTIVATE = 'HOME_CONTENT_SPINNER_DEACTIVATE ';

//for redux reducer
export const SET_HOME_ABOUT_DATA = 'SET_HOME_ABOUT_DATA';
export const SET_HOME_SLIDER_DATA = 'SET_HOME_SLIDER_DATA';