export const CLOSE_MODAL_WINDOW = 'CLOSE_MODAL_WINDOW';
export const SHOW_MODAL_WINDOW = 'SHOW_MODAL_WINDOW';
export const SHOW_LOAD_MODAL_WINDOW = 'SHOW_LOAD_MODAL_WINDOW';
export const CLOSE_LOAD_MODAL_WINDOW = 'CLOSE_LOAD_MODAL_WINDOW';

export const SHOW_MENU = 'SHOW_MENU';
export const CLOSE_MENU = 'CLOSE_MENU';