// for redux-saga
export const LOAD_NOTIFICATION_DATA = 'LOAD_NOTIFICATION_DATA';
    //for school admission
export const LOAD_SCHOOL_ADMISSION_DATA = 'LOAD_SCHOOL_ADMISSION_DATA';

// for redux-reducer
export const SET_NOTIFICATION_DATA = 'SET_NOTIFICATION_DATA';
export const NOTIFICATION_SPINNER_ACTIVATE = 'NOTIFICATION_SPINNER_ACTIVATE';
export const NOTIFICATION_SPINNER_DEACTIVATE = 'NOTIFICATION_SPINNER_DEACTIVATE';
export const SET_CURRENT_NOTICE_FILTER_VALUE = 'SET_CURRENT_NOTICE_FILTER_VALUE';

    //for school admission
export const SET_SCHOOL_ADMISSION_DATA = 'SET_SCHOOL_ADMISSION_DATA';
export const SCHOOL_ADMISSION_SPINNER_ACTIVATE =  'SCHOOL_ADMISSION_SPINNER_ACTIVATE';
export const SCHOOL_ADMISSION_SPINNER_DEACTIVATE =  'SCHOOL_ADMISSION_SPINNER_DEACTIVATE';