// for redux-saga
export const LOAD_NOTIFICATION_DATA = 'LOAD_NOTIFICATION_DATA';

// for redux-reducer
export const SET_NOTIFICATION_DATA = 'SET_NOTIFICATION_DATA';
export const NOTIFICATION_SPINNER_ACTIVATE = 'NOTIFICATION_SPINNER_ACTIVATE';
export const NOTIFICATION_SPINNER_DEACTIVATE = 'NOTIFICATION_SPINNER_DEACTIVATE';

