export const SCHOOL_DOCS_LOAD_DATA = "SCHOOL_DOCS_LOAD_DATA";
export const SCHOOL_DOCS_SET_DATA = "SCHOOL_DOCS_SET_DATA";
export const SCHOOL_DOCS_ACTIVATE_SPINNER = "SCHOOL_DOCS_ACTIVATE_SPINNER";
export const SCHOOL_DOCS_DEACTIVATE_SPINNER = "SCHOOL_DOCS_DEACTIVATE_SPINNER";