// for redux-saga
export const LOAD_TEACHERS_DATA = 'LOAD_TEACHERS_DATA';

// for redux-reducer
export const SET_TEACHERS_DATA = 'SET_TEACHERS_DATA';
export const TEACHERS_SPINNER_ACTIVATE = 'TEACHERS_SPINNER_ACTIVATE';
export const TEACHERS_SPINNER_DEACTIVATE = 'TEACHERS_SPINNER_DEACTIVATE';

