// for redux-saga
export const LOAD_TIMETABLE_DATA = 'LOAD_TIMETABLE_DATA';

// for redux-reducer
export const SET_TIMETABLE_DATA = 'SET_TIMETABLE_DATA';
export const TIMETABLE_SPINNER_ACTIVATE = 'TIMETABLE_SPINNER_ACTIVATE';
export const TIMETABLE_SPINNER_DEACTIVATE = 'TIMETABLE_SPINNER_DEACTIVATE';

